/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainUI.java
 *
 * Created on Dec 23, 2011, 11:30:31 AM
 */

/**
 *
 * @author d
 */
public class MainUI extends javax.swing.JFrame {

    /** Creates new form MainUI */
    public MainUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPub = new javax.swing.JMenuItem();
        mnuPMod = new javax.swing.JMenuItem();
        mnuPDel = new javax.swing.JMenuItem();
        mnuPNav = new javax.swing.JMenuItem();
        mnuIssue = new javax.swing.JMenu();
        mnuLib = new javax.swing.JMenuItem();
        mnuLibEdit = new javax.swing.JMenuItem();
        mnuLibDel = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuReturn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuMemb = new javax.swing.JMenuItem();
        mnuMMod = new javax.swing.JMenuItem();
        mnuMDel = new javax.swing.JMenuItem();
        mnuMNav = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuABList = new javax.swing.JMenuItem();
        mnuLBList = new javax.swing.JMenuItem();
        mnuMList = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuQuit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Indian");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Managment System");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Indian Library");

        jLabel4.setFont(new java.awt.Font("Broadway", 1, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("***");

        jLabel5.setFont(new java.awt.Font("Broadway", 1, 29)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("***");

        jMenu1.setText("Publisher");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuPub.setText("Publisher Console");
        mnuPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPubActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPub);

        mnuPMod.setText("Modification");
        mnuPMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPModActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPMod);

        mnuPDel.setText("Deletion");
        mnuPDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPDelActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPDel);

        mnuPNav.setText("Record Nevegation");
        mnuPNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPNavActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPNav);

        jMenuBar1.add(jMenu1);

        mnuIssue.setText("Book");

        mnuLib.setText("Book Console");
        mnuLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibActionPerformed(evt);
            }
        });
        mnuIssue.add(mnuLib);

        mnuLibEdit.setText("Modifcation");
        mnuLibEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibEditActionPerformed(evt);
            }
        });
        mnuIssue.add(mnuLibEdit);

        mnuLibDel.setText("Deletion");
        mnuIssue.add(mnuLibDel);

        jMenuItem2.setText("Book Issue");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuIssue.add(jMenuItem2);

        mnuReturn.setText("Book Return");
        mnuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReturnActionPerformed(evt);
            }
        });
        mnuIssue.add(mnuReturn);

        jMenuBar1.add(mnuIssue);

        jMenu3.setText("Member");

        mnuMemb.setText("Member Console");
        mnuMemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMembActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMemb);

        mnuMMod.setText("Modification");
        mnuMMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMModActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMMod);

        mnuMDel.setText("Deletion");
        mnuMDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMDelActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMDel);

        mnuMNav.setText("Record Nevegation");
        mnuMNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMNavActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMNav);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Report");

        mnuABList.setText("Available Book List");
        mnuABList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuABListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuABList);

        mnuLBList.setText("Issued Book List");
        mnuLBList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLBListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuLBList);

        mnuMList.setText("Member List");
        mnuMList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuMList);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quit");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        mnuQuit.setText("Exit Application");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });
        jMenu5.add(mnuQuit);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

      
}//GEN-LAST:event_jMenu1ActionPerformed

    private void mnuPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPubActionPerformed
        // TODO add your handling code here:
        new pubUI().setVisible(true);
        new pubUI().getAlignmentX();

    }//GEN-LAST:event_mnuPubActionPerformed

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuQuitActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5ActionPerformed

    private void mnuPModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPModActionPerformed
        // TODO add your handling code here:
        new PubEditUI().setVisible(true);

    }//GEN-LAST:event_mnuPModActionPerformed

    private void mnuPDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPDelActionPerformed
        // TODO add your handling code here:
        new PubDelUI().setVisible(true);
    }//GEN-LAST:event_mnuPDelActionPerformed

    private void mnuPNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPNavActionPerformed
        // TODO add your handling code here:
        new PubNavUI().setVisible(true);
    }//GEN-LAST:event_mnuPNavActionPerformed

    private void mnuLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibActionPerformed
        // TODO add your handling code here:
        new LibUI().setVisible(true);
    }//GEN-LAST:event_mnuLibActionPerformed

    private void mnuLibEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibEditActionPerformed
        // TODO add your handling code here:
        new LibEditUI().setVisible(true);

    }//GEN-LAST:event_mnuLibEditActionPerformed

    private void mnuMembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMembActionPerformed
        // TODO add your handling code here:
        new MembUI().setVisible(true);
    }//GEN-LAST:event_mnuMembActionPerformed

    private void mnuMModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMModActionPerformed
           new MembEditUI().setVisible(true);
    }//GEN-LAST:event_mnuMModActionPerformed

    private void mnuMDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMDelActionPerformed
           new MembDelUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMDelActionPerformed

    private void mnuMNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMNavActionPerformed
        // TODO add your handling code here:
        new MembNavUI().setVisible(true);
    }//GEN-LAST:event_mnuMNavActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new IssueUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReturnActionPerformed
        // TODO add your handling code here:
        new ReturnUI().setVisible(true);
    }//GEN-LAST:event_mnuReturnActionPerformed

    private void mnuABListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuABListActionPerformed
        // TODO add your handling code here:
        new ABListUI().setVisible(true);
    }//GEN-LAST:event_mnuABListActionPerformed

    private void mnuLBListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLBListActionPerformed
        // TODO add your handling code here:
        new IBListUI().setVisible(true);
    }//GEN-LAST:event_mnuLBListActionPerformed

    private void mnuMListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMListActionPerformed
        // TODO add your handling code here:
        new MListUI().setVisible(true);
    }//GEN-LAST:event_mnuMListActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuABList;
    private javax.swing.JMenu mnuIssue;
    private javax.swing.JMenuItem mnuLBList;
    private javax.swing.JMenuItem mnuLib;
    private javax.swing.JMenuItem mnuLibDel;
    private javax.swing.JMenuItem mnuLibEdit;
    private javax.swing.JMenuItem mnuMDel;
    private javax.swing.JMenuItem mnuMList;
    private javax.swing.JMenuItem mnuMMod;
    private javax.swing.JMenuItem mnuMNav;
    private javax.swing.JMenuItem mnuMemb;
    private javax.swing.JMenuItem mnuPDel;
    private javax.swing.JMenuItem mnuPMod;
    private javax.swing.JMenuItem mnuPNav;
    private javax.swing.JMenuItem mnuPub;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JMenuItem mnuReturn;
    // End of variables declaration//GEN-END:variables

}
